import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { MapContextProvider } from "./Context/MapContext";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <MapContextProvider>
      <html lang="en">
        <body className={font.className}>{children}</body>
      </html>
    </MapContextProvider>
  );
}
